## <font color="maroon"><h4 align="center">Pandas Group By: Exercise</font>

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'movies_data.csv' and store it in a variable 'df'

In [3]:
#read the excel file

df = pd.read_csv('movies_data.csv')

#show the df

df.head()

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD

### <font color="purple">**Question2**</font>
- Group the dataframe by 'industry' and store it in a variable 'g'
- Get the size of each grouped category
- Get all the data related to "Bollywood"

In [9]:
#group by 'industry' and store it in variable 'g'
 
g = df.groupby('industry')

#get the size of each category

g.size()

industry
Bollywood    17
Hollywood    20
dtype: int64

In [10]:
#get the 'Bollywood' group

g.get_group('Bollywood')

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.0,12.5,Billions,INR
21,107,Dilwale Dulhania Le Jayenge,Bollywood,Hindi,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR
22,108,3 Idiots,Bollywood,Hindi,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR
23,109,Kabhi Khushi Kabhie Gham,Bollywood,Hindi,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR
24,110,Bajirao Mastani,Bollywood,Hindi,2015,7.2,NaN,1.4,3.5,Billions,INR
25,128,Taare Zameen Par,Bollywood,Hindi,2007,8.3,NaN,120.0,1350.0,Millions,INR
26,129,Munna Bhai M.B.B.S.,Bollywood,Hindi,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR
27,130,PK,Bollywood,Hindi,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR
28,131,Sanju,Bollywood,Hindi,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR
29,135,The Kashmir Files,Bollywood,Hindi,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR
30,136,Bajrangi Bhaijaan,Bollywood,Hindi,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR
31,139,Race 3,Bollywood,Hindi,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR
32,140,Shershaah,Bollywood,Hindi,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR
33,127,Pather Panchali,Bollywood,Bengali,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR
34,132,Pushpa: The Rise - Part 1,Bollywood,Telugu,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR
35,133,RRR,Bollywood,Telugu,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR
36,134,Baahubali: The Beginning,Bollywood,Telugu,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR

### <font color="purple">**Question3: Group data using custom function:**</font>
Here, the requirement is to create four groups based on **"imdb_rating"**

- 1 <= imdb_rating <= 3.9 ---> 'Poor'
- 4 <= imdb_rating <= 7.9 ---> 'Average'
- 8 <= imdb_rating <= 10 --->  'Good'
- If none of above satisfy, then return 'others'

In [ ]:
#complete the function 'grouper'

def grouper(df, idx, col):
    '''
        This function returns category based on imdb_rating
    '''

In [ ]:
#groupby based on the grouper function and store it in a variable 'g'
#Note: use the imdb_rating column

#iterate through the 'g' and print all the groups